app/routes.py
from flask import Blueprint, render_template , redirect , url_for , request , flash
from .models import *
from . import db
from werkzeug.exceptions import BadRequest
import random
from flask_bcrypt import generate_password_hash , check_password_hash
from flask_login import current_user , login_user , logout_user

main = Blueprint('main', __name__)


# TYPES_OF_GROCERY = {"vegetable" : Vegetable , "fruit": Fruit}
ALL_PRODUCT = [item for item in Product.query.all()]
top_six_product = random.sample(population=ALL_PRODUCT ,k=6)
random.shuffle(ALL_PRODUCT)



buylist = []



@main.route("/user")
def hello():
    print(current_user.is_authenticated)
    if current_user.is_authenticated:
        return f"user = {current_user} , {current_user.cart_items} buylsit = {buylist} "
    else:
        return f"user = {current_user} , buylsit = {buylist} "


def userId():
    if not current_user.is_authenticated:  
        return 0                                # id = 0  for (when not logegd in)
    else:
        return current_user.id

def addBuylistToCart():
    if buylist:
        itemExistInCart = False
        for product in buylist:
            productToAdd = Product.query.get(id)

            if product.product_id == productToAdd.id:                         # item already exists in buylist
                product.quantity += 1
                product.total_price += product.price
                itemExistInCart = True
                db.session.commit()       
                break
            if not itemExistInCart:
                db.session.add(product)
                db.session.commit()       

def calculate_total_price():
    total_price= 0
    if not current_user.is_authenticated:           # user is not logged in
        if buylist is None :
            return 0
        else:
            for product in buylist:
                total_price += product.total_price 
            return total_price
    
    else:                                           # user is logged in
        if current_user.cart_items is None :
            return 0
        else:
            for product in current_user.cart_items:
                total_price += product.total_price 
            return total_price

# Search bar
def search(product):
    # item = request.form.get('product')
    # print(item)
    searched_items = []

    for item in Product.query.all():
        name = item.name.lower()
        print(name.__eq__(product.lower()))
        if  name.__eq__(product.lower()):
            searched_items.append(item)
        if name.__contains__(product.lower()):
            searched_items.append(item)
    return searched_items

@main.route("/signup" , methods=['POST' , 'GET'])
def signup():
    # if current_user.is_authenticated():
    if request.method == 'GET':
        return render_template('signup.html')
    else:
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        hashed_password  = generate_password_hash(password= password)

        
        user = User.query.filter_by(email = email).first()
        if user:
            flash(message= 'Account already exist')
            return redirect(url_for('main.login'))
        else:
            new_user = User(username = username , email = email , password = hashed_password)
            db.session.add(new_user)
            db.session.commit()

            login_user(new_user)
            # if user added some item to cart it added to therir cart when they login
            addBuylistToCart()
            flash(f'Logged in Successfully {current_user.username}')
            return redirect(url_for('main.index'))

@main.route("/login", methods=['POST' , 'GET'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        email = request.form.get('email')
        password = request.form.get('password')

        print(email ,password)
        try:
            user = User.query.filter_by(email = email).first()
            print(user)
            if user == None:
                flash('Please create account first')
                return redirect(url_for('main.signup'))
            if user != None and check_password_hash(pw_hash = user.password , password=password):
                login_user(user = user)
                # if user added some item to cart it added to therir cart when they login
                addBuylistToCart()

                flash(f'Logged in Successfully {current_user.username}')
                return redirect(url_for('main.index'))
            else:
                flash('Either email or password is wrong try again!')
                return redirect(url_for('main.login'))
        except:
            flash('Please create account first')
            return redirect(url_for('main.signup'))
        


@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))

# def item_exist_in_buylist():
#     productToAdd = TYPES_OF_GROCERY[type].query.get(id)
#     for index , product in enumerate(buylist):
#         print(product['product'].name , productToAdd)
#         if product.__getitem__('product') == productToAdd:
#             buylist[index]['quantity'] += 1
#             buylist[index]['total_price'] += productToAdd.price
#             return redirect(url_for('index'))

@main.errorhandler(BadRequest)
@main.route("/search/<page>/<product>" , methods=['GET'])
def main_search(product , page):

    searched_items = search(product=product)

    if page =="shop":
        return render_template("shop.html" ,all_product = searched_items  )
    if page == 'groceries':
        return render_template("search_result.html" ,searched_items = searched_items , )
    else:
        return 'bad request!', 400


@main.errorhandler(BadRequest)
@main.route('/inc/<itemindex>' ,  methods=['POST' , 'GET'])
def inc_quantity_price(itemindex):
    # itemindex = index-1
    if request.method == 'POST':
        itemindex = int(itemindex)
        if current_user.is_authenticated:
            current_user.cart_items[itemindex].quantity += 1
            current_user.cart_items[itemindex].total_price += current_user.cart_items[itemindex].price

            db.session.commit()
            print(f'{current_user.cart_items[itemindex]}  is inc')
            return redirect(url_for('main.cart'))
        else:
            buylist[itemindex].quantity += 1
            buylist[itemindex].total_price += buylist[itemindex].price

            return redirect(url_for('main.cart'))
    else:
        return 'bad request!', 400



@main.errorhandler(BadRequest)
@main.route('/dec/<itemindex>', methods=['POST' , 'GET'])
def dec_quantity_price(itemindex):
    # itemindex = index -1 
    if request.method == 'POST':
        itemindex = int(itemindex)
        if current_user.is_authenticated:
            if current_user.cart_items[itemindex] > 1:
                current_user.cart_items[itemindex].quantity -= 1
                current_user.cart_items[itemindex].total_price -= current_user.cart_items[itemindex].price

                db.session.commit()
                print(f'{current_user.cart_items[itemindex]}  is dec')
            else:   # removing the cart item
                cart_item = UserCart.query.get_or_404(int(current_user.cart_items[itemindex].id))
                db.session.delete(cart_item)

                db.session.commit()
            return redirect(url_for('main.cart'))
        else:
            if buylist[itemindex] > 1:
                buylist[itemindex].quantity -= 1
                buylist[itemindex].total_price -= buylist[itemindex].price

            else:   # removing the cart item
                buylist.pop(itemindex)
            return redirect(url_for('main.cart'))
    else:
        return 'bad request!', 400






@main.route("/")      # if url address start with this '/' print  'Hello, World'
def index():
    return render_template("index.html",
                            all_product = ALL_PRODUCT ,top_six_product = top_six_product )


@main.route("/404")      # if url address start with this '/' print  'Hello, World'
def error():
    return render_template("404.html")

@main.route("/addtocart/<id>")      # if url address start with this '/' print  'Hello, World'
def addtocart(id):
    productToAdd = Product.query.get(id)
    user_id = userId()
    # using func  user_id() for getting current_user.id 
    cart_item = UserCart(name = productToAdd.name , image = productToAdd.image, price = productToAdd.price, 
                         description = productToAdd.description , type = productToAdd.type , rating = productToAdd.rating, 
                         quantity = 1 , total_price = productToAdd.price , user_id = user_id , product_id = productToAdd.id)
    if current_user.is_authenticated:
        itemExistInCart = False
        for product in current_user.cart_items:
            if product.product_id == productToAdd.id:                         # item already exists in buylist
                product.quantity += 1
                product.total_price += product.price
                itemExistInCart = True
                db.session.commit()
                break
        if not itemExistInCart:
            db.session.add(cart_item)
            db.session.commit()
    else:
        itemExistInCart = False
        for product in buylist:
            if product.product_id == productToAdd.id:                         # item already exists in buylist
                product.quantity += 1
                product.total_price += product.price
                itemExistInCart = True
                break
        if not itemExistInCart:
            buylist.append(cart_item)
    return redirect(url_for('main.index'))


@main.route("/cart" )      # if url address start with this '/' print  'Hello, World'
def cart():
    # if request.method == "POST":
    if current_user.is_authenticated:                       # USer is logegd in

app/templates/cart.html
{% include 'header.html' %}


        <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Cart</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Pages</a></li>
                <li class="breadcrumb-item active text-white">Cart</li>
            </ol>
        </div>
        <!-- Single Page Header End -->


        <!-- Cart Page Start -->
        <div class="container-fluid py-5">
            <div class="container py-5">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Products</th>
                                <th scope="col">Name</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                                <th scope="col">Handle</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in product_to_buy %}
                            <tr>
                                <th scope="row">
                                    <div class="d-flex align-items-center">
                                        <img src="{{url_for('static', filename=product.image)}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                    </div>
                                </th>
                                <td>
                                    <p class="mb-0 mt-4">{{product.name}}</p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4 product-price" data-price="{{product.price}}">{{product.price}} ₹</p>
                                </td>
                                <td>
                                    <div class="input-group quantity mt-4" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <form method="POST" id="updateQuantityForm-{{ loop.index0 }}">
                                                <div class="d-flex align-items-center">
                                                    <!-- Minus Button -->
                                                    <a class="btn btn-sm btn-minus rounded-circle bg-light border me-2" href="javascript:void(0);" onclick="submitForm('{{ url_for('main.dec_quantity_price', itemindex=loop.index0) }}')">
                                                        <i class="fa fa-minus"></i>
                                                    </a>
                                            
                                                    <!-- Quantity Input -->
                                                    <input type="text" class="form-control form-control-sm text-center border-0 product-quantity" value="{{product.quantity}}">
                                            
                                                    <!-- Plus Button -->
                                                    <a class="btn btn-sm btn-plus rounded-circle bg-light border ms-2" href="javascript:void(0);" onclick="submitForm('{{ url_for('main.inc_quantity_price', itemindex=loop.index0) }}')">
                                                        <i class="fa fa-plus"></i>
                                                    </a>
                                                </div>
                                            </form>
                                            
                                            <script>
                                                function submitForm(action) {
                                                    const form = document.createElement('form');
                                                    form.method = 'POST';
                                                    form.action = action;
                                            
                                                    document.body.appendChild(form);
                                                    form.submit();
                                                }
                                            </script>
                                            

                                            
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4 subtotal-price">{{product.total_price}} ₹</p>
                                </td>
                                <td>
                                    <button class="btn btn-md rounded-circle bg-light border mt-4">
                                        <i class="fa fa-times text-danger"></i>
                                    </button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        
                <!-- Total Price Section -->
                <div class="d-flex justify-content-end">
                    <h4>Total: <span id="total-price">{{total_price}}₹</span></h4>
                </div>
        
        
                <div class="mt-5">
                    <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code">
                    <button class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="button">Apply Coupon</button>
                </div>
                <div class="row g-4 justify-content-end">
                    <div class="col-8"></div>
                    <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                        <div class="bg-light rounded">
                            <div class="p-4">
                                <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                                <div class="d-flex justify-content-between mb-4">
                                    <h5 class="mb-0 me-4">Subtotal:</h5>
                                    <p class="mb-0" id="cart-subtotal">₹{{total_price}}</p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <h5 class="mb-0 me-4">Shipping</h5>
                                    <div class="">
                                        <p class="mb-0">Flat rate: ₹3.00</p>
                                    </div>
                                </div>
                                <p class="mb-0 text-end">Shipping to Ukraine.</p>
                            </div>
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                                <h5 class="mb-0 ps-4 me-4">Total</h5>
                                <p class="mb-0 pe-4" id="final-total">₹{{total_price + 3}}</p>
                            </div>
                            <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="button">Proceed Checkout</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

                <!-- cart ends here -->
{% include 'footer.html' %}

app/templates/header.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Fruitables - Vegetable Website Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{{url_for('static', filename='lib/lightbox/css/lightbox.min.css')}}" rel="stylesheet">
        <link href="{{url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        
        <!-- Template Stylesheet -->
        <link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">
    </head>
    
    <body>
        
        <!-- Spinner Start -->
        <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div>
        <!-- Spinner End -->
        
        
        <!-- {{url_for('static', filename='css/style.css')}} -->
        <!-- Navbar start -->
        <div class="container-fluid fixed-top">
            <div class="container topbar bg-primary d-none d-lg-block">
                <div class="d-flex justify-content-between">
                    <div class="top-info ps-2">
                        <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">123 Street, New York</a></small>
                        <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
                    </div>
                    <div class="top-link pe-2">
                        <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                        <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                        <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
                    </div>
                </div>
            </div>
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a href="{{url_for('main.index')}}" class="navbar-brand"><h1 class="text-primary display-6">Fruitables</h1></a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a href="{{url_for('main.index')}}" class="nav-item nav-link active">Home</a>
                            <a href="{{url_for('main.shop')}}" class="nav-item nav-link">Shop</a>
                            <a href="{{url_for('main.shop_detail')}}" class="nav-item nav-link">Shop Detail</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                    <a href="{{url_for('main.cart')}}" class="dropdown-item">Cart</a>
                                    <a href="{{url_for('main.checkout')}}" class="dropdown-item">Checkout</a>
                                    <a href="{{url_for('main.testimonial')}}" class="dropdown-item">Testimonial</a>
                                    <a href="{{url_for('main.error')}}" class="dropdown-item">404 Page</a>
                                </div>
                            </div>
                            <a href="{{url_for('main.contact')}}" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="d-flex m-3 me-0">
                            <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>

                            <a href="{{url_for('main.cart')}}" class="position-relative me-4 my-auto">
                                <i class="fa fa-shopping-bag fa-2x"></i>
                                <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1" style="top: -5px; left: 15px; height: 20px; min-width: 20px;">3</span>
                            </a>
                            <a href="{{url_for('main.login')}}" class="my-auto">
                                <i class="fas fa-user fa-2x"></i>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->

        <!-- Modal Search Start -->
        <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <div class="input-group w-75 mx-auto d-flex">
                            <input type="search" id="product-search" name="product" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                            <span id="search-icon-1" class="input-group-text p-3" onclick="Search()" style="cursor: pointer;">
                                <i class="fa fa-search"></i>
                            </span>
                            
                            <script>
                                function Search() {
                                    const product = document.getElementById("product-search").value;
                                    if (product) {
                                        // Redirect with the search term as a query parameter
                                        window.location.href = `/search/groceries/${encodeURIComponent(product)}`;
                                    }
                                }
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Search End -->

app/templates/login.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <u class=flashes>                     # delete ul to remove dot
    {% for message in messages %}
      {{ message }}
    {% endfor %}
  {% endif %}
{% endwith %}
<form action="{{url_for('main.login')}}" ,  method="post">
    <input type="email" name="email" id="">
    <input type="password" name="password" id="">
    <input type="submit" , value="login">
</form>

<!-- <button onclick="{{url_for('main.logout')}}">logout</button> -->

<a href="{{ url_for('main.logout') }}" type="button" style="display: block; width: 115px; height: 25px; background: #4E9CAF; padding: 10px; text-align: center; border-radius: 5px; color: white; font-weight: bold; line-height: 25px;">logout</a>

app/templates/search_result.html
{% include 'header.html' %}


        <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Search</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Pages</a></li>
                <li class="breadcrumb-item active text-white">Search</li>
            </ol>
        </div>
        <!-- Single Page Header End -->


        <!-- Cart Page Start -->
        <div class="container-fluid py-5">
            <div class="container py-5">
                <div class="table-responsive">
                                            
                            <div class="col-lg-9">
                                <div class="row g-4 justify-content-center">
                                    {% for product in searched_items  %}
                                    <div class="col-md-6 col-lg-4 col-xl-3">
                                         <div class="rounded position-relative fruite-item">
                                             <div class="fruite-img">
                                                 <img src="{{url_for('static', filename=product.image)}}" class="img-fluid w-100 rounded-top" alt="">
                                             </div>
                                             <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">{{product.type}}</div>
                                             <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                                 <h4>{{product.name}}</h4>
                                                 <p>{{product.description}}</p>
                                                 <div class="d-flex justify-content-between flex-lg-wrap">
                                                     <p class="text-dark fs-5 fw-bold mb-0"> ₹{{product.price}}/ kg</p>
                                                     <a href="{{url_for('main.addtocart' , type = product.type , id= product.id)}}" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Add to cart</a>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                                      {% endfor %}                                  
                            
                                </div>
                            </div>

                        </tbody>
                    </table>
                </div>
        


            </div>
        </div>

                <!-- cart ends here -->
{% include 'footer.html' %}

app/templates/signup.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <u class=flashes>                     # delete ul to remove dot
    {% for message in messages %}
      {{ message }}
    {% endfor %}
  {% endif %}
{% endwith %}

<h1>Create new account</h1>
<form action="{{url_for('main.signup')}}" ,  method="post" >
    <input type="" name="username" id="">
    <input type="email" name="email" id="">
    <input type="password" name="password" id="">
    <input type="submit" , value="Signup">
</form>

<button onclick="{{url_for('main.logout')}}">logout</button>